# Generated by Django 4.2.1 on 2023-05-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('query', models.TextField(max_length=250)),
                ('file', models.FileField(upload_to='cv/')),
            ],
        ),
    ]
