# Generated by Django 4.2.1 on 2023-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(upload_to='media/cv'),
        ),
    ]
